apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: vwarcou
spec:
  containers:
    - name: hello
      image: arquitectura/hello
      imagePullPolicy: Always
      command: [ "tail -f /dev/null" ]



  imagePullSecrets:
    - name: regdcsrv2

    