name: Github Registry

on: [push, pull_request, workflow_dispatch]

env:
  IMAGE_NAME: alpine


jobs:
  build-and-push-images:
    runs-on: [self-hosted, linux, x64]
    # Asignamos los permisos sobre los recursos de GitHub
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            dcsrv2.contadepto.net:5000/${{ env.IMAGE_NAME}}
          tags: |
            latest
            type=sha

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master' # Solo master
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Local registry
        if: github.ref == 'refs/heads/master' # Solo master
        uses: docker/login-action@v1
        with:
          registry: dcsrv2.contadepto.net:5000/v2
          username: ${{ secrets.LOCAL_USERNAME }}
          password: ${{ secrets.LOCAL_PASSWORD }}

      - name: dig 
        run: | 
          dig dcsrv2.contadepto.net

      - name: Build 
      
        run: docker build . -t dcsrv2.contadepto.net:5000/alpine
        shell: bash
          

      - name: push 
      
        run: docker push dcsrv2.contadepto.net:5000/alpine






      - name: kubectl deploy 
        run: | 
          kubectl apply -f create-pod.yaml
