apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: vwarcou
spec:
  containers:
    - name: hello
      image: arquitectura/hello
      imagePullPolicy: Always
      command: [ "top" ]


  imagePullSecrets:
    - name: regcred